apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ${project.artifactId}
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  rules:
  - http:
      paths:
      - path: /front
        backend:
          serviceName: ${project.artifactId}
          servicePort: 8080